apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: pandiaraja2/testskaffold
    docker:
      dockerfile: Dockerfile
deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
    - k8s-app.yml
